name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      artifact_version:
        description: "Select Artifact Version"
        required: true
        type: choice
        options:
          - v1.0.0
          - v1.1.0
          - v1.2.0
          - latest
      dev_server:
        description: "Select Dev Server"
        required: true
        type: choice
        options:
          - dev-server-1
          - dev-server-2
          - dev-server-3

jobs:
  print-selection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print selected inputs
        run: |
          echo "Selected Artifact Version: ${{ github.event.inputs.artifact_version }}"
          echo "Selected Dev Server: ${{ github.event.inputs.dev_server }}"
          echo "Current Working Directory:"
          pwd

      - name: List directory
        run: ls -la

      - name: PWD
        run: pwd
